// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: v1/components/enum.proto

package componentsV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnableStatus int32

const (
	// 默认值
	EnableStatus_ENABLE_STATUS_DEFAULT EnableStatus = 0
	// 启用
	EnableStatus_ENABLE EnableStatus = 1
	// 禁用
	EnableStatus_DISABLE EnableStatus = 2
)

// Enum value maps for EnableStatus.
var (
	EnableStatus_name = map[int32]string{
		0: "ENABLE_STATUS_DEFAULT",
		1: "ENABLE",
		2: "DISABLE",
	}
	EnableStatus_value = map[string]int32{
		"ENABLE_STATUS_DEFAULT": 0,
		"ENABLE":                1,
		"DISABLE":               2,
	}
)

func (x EnableStatus) Enum() *EnableStatus {
	p := new(EnableStatus)
	*p = x
	return p
}

func (x EnableStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnableStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_components_enum_proto_enumTypes[0].Descriptor()
}

func (EnableStatus) Type() protoreflect.EnumType {
	return &file_v1_components_enum_proto_enumTypes[0]
}

func (x EnableStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnableStatus.Descriptor instead.
func (EnableStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_components_enum_proto_rawDescGZIP(), []int{0}
}

type MenuType int32

const (
	// 默认值
	MenuType_MENU_TYPE_DEFAULT MenuType = 0
	// 目录
	MenuType_DIRECTORY MenuType = 1
	// 菜单
	MenuType_MENU MenuType = 2
	// 按钮
	MenuType_BUTTON MenuType = 3
)

// Enum value maps for MenuType.
var (
	MenuType_name = map[int32]string{
		0: "MENU_TYPE_DEFAULT",
		1: "DIRECTORY",
		2: "MENU",
		3: "BUTTON",
	}
	MenuType_value = map[string]int32{
		"MENU_TYPE_DEFAULT": 0,
		"DIRECTORY":         1,
		"MENU":              2,
		"BUTTON":            3,
	}
)

func (x MenuType) Enum() *MenuType {
	p := new(MenuType)
	*p = x
	return p
}

func (x MenuType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MenuType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_components_enum_proto_enumTypes[1].Descriptor()
}

func (MenuType) Type() protoreflect.EnumType {
	return &file_v1_components_enum_proto_enumTypes[1]
}

func (x MenuType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MenuType.Descriptor instead.
func (MenuType) EnumDescriptor() ([]byte, []int) {
	return file_v1_components_enum_proto_rawDescGZIP(), []int{1}
}

type MenuHidden int32

const (
	// 默认值
	MenuHidden_MENU_HIDDEN_DEFAULT MenuHidden = 0
	// 隐藏
	MenuHidden_TRUE MenuHidden = 1
	// 显示
	MenuHidden_FALSE MenuHidden = 2
)

// Enum value maps for MenuHidden.
var (
	MenuHidden_name = map[int32]string{
		0: "MENU_HIDDEN_DEFAULT",
		1: "TRUE",
		2: "FALSE",
	}
	MenuHidden_value = map[string]int32{
		"MENU_HIDDEN_DEFAULT": 0,
		"TRUE":                1,
		"FALSE":               2,
	}
)

func (x MenuHidden) Enum() *MenuHidden {
	p := new(MenuHidden)
	*p = x
	return p
}

func (x MenuHidden) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MenuHidden) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_components_enum_proto_enumTypes[2].Descriptor()
}

func (MenuHidden) Type() protoreflect.EnumType {
	return &file_v1_components_enum_proto_enumTypes[2]
}

func (x MenuHidden) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MenuHidden.Descriptor instead.
func (MenuHidden) EnumDescriptor() ([]byte, []int) {
	return file_v1_components_enum_proto_rawDescGZIP(), []int{2}
}

var File_v1_components_enum_proto protoreflect.FileDescriptor

var file_v1_components_enum_proto_rawDesc = []byte{
	0x0a, 0x18, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f,
	0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x56, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x76, 0x31, 0x2f, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x42, 0x0a, 0x0c, 0x45, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x4e,
	0x41, 0x42, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x45, 0x46, 0x41,
	0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x02, 0x2a, 0x46,
	0x0a, 0x08, 0x4d, 0x65, 0x6e, 0x75, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x4d, 0x45,
	0x4e, 0x55, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x59, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x4d, 0x45, 0x4e, 0x55, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x55,
	0x54, 0x54, 0x4f, 0x4e, 0x10, 0x03, 0x2a, 0x3a, 0x0a, 0x0a, 0x4d, 0x65, 0x6e, 0x75, 0x48, 0x69,
	0x64, 0x64, 0x65, 0x6e, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x45, 0x4e, 0x55, 0x5f, 0x48, 0x49, 0x44,
	0x44, 0x45, 0x4e, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x54, 0x52, 0x55, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x41, 0x4c, 0x53, 0x45,
	0x10, 0x02, 0x42, 0x57, 0x5a, 0x55, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x66, 0x79, 0x6e, 0x6e, 0x74, 0x61, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2d, 0x63, 0x72, 0x75, 0x64, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x3b, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_v1_components_enum_proto_rawDescOnce sync.Once
	file_v1_components_enum_proto_rawDescData = file_v1_components_enum_proto_rawDesc
)

func file_v1_components_enum_proto_rawDescGZIP() []byte {
	file_v1_components_enum_proto_rawDescOnce.Do(func() {
		file_v1_components_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_components_enum_proto_rawDescData)
	})
	return file_v1_components_enum_proto_rawDescData
}

var file_v1_components_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_v1_components_enum_proto_goTypes = []interface{}{
	(EnableStatus)(0), // 0: componentsV1.EnableStatus
	(MenuType)(0),     // 1: componentsV1.MenuType
	(MenuHidden)(0),   // 2: componentsV1.MenuHidden
}
var file_v1_components_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_components_enum_proto_init() }
func file_v1_components_enum_proto_init() {
	if File_v1_components_enum_proto != nil {
		return
	}
	file_v1_components_dictionary_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_components_enum_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_components_enum_proto_goTypes,
		DependencyIndexes: file_v1_components_enum_proto_depIdxs,
		EnumInfos:         file_v1_components_enum_proto_enumTypes,
	}.Build()
	File_v1_components_enum_proto = out.File
	file_v1_components_enum_proto_rawDesc = nil
	file_v1_components_enum_proto_goTypes = nil
	file_v1_components_enum_proto_depIdxs = nil
}
